name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true 
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        username: fangyi-zhou
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: sessionstar/oopsla20-artifact/artifact
        tags: latest
